Multiple packages enhancement
scolladon/sfdc-merge-package pull request #1
Opened 2022-09-14 13:43 UTC by rgarlik

Hey all,
I've changed the `-p` flag to accept a list of files in a more intuitive way by making it a [variadic option](https://github.com/tj/commander.js#variadic-option). Most CLI applications usually behave this way.

Before, you had to write the `-p` flag before every single file you wanted to package:
```sh
smp -p ./package1.xml -p ./package2.xml -p ./package3.xml -o ./combined-package.xml
```

Now you only have to write the `-p` flag once and then provide a list of files:
```sh
smp -p ./package1.xml ./package2.xml ./package3.xml -o ./combined-package.xml
```

This is also backwards compatible with the old way of doing things as shown in the examples in `tj/commander` in the link I've provided above.
I've also updated the `README.md` to reflect these changes.

2022-09-14 15:22 UTC, scolladon requested changes
Good pull request, good work!
Few suggestion to make the code simpler
We can discuss about it

2022-09-14 15:22 UTC, scolladon commented on index.js
> +  if(typeof config.packages === 'undefined' || config.packages === null || config.packages === []) {
**suggestion:** test for empty array

```suggestion
  if(!Array.isArray(config.packages) || config.packages.length === 0) {
```

2022-09-16 08:42 UTC, rgarlik commented on index.js
> +  if(typeof config.packages === 'undefined' || config.packages === null || config.packages === []) {
yeah, that's much better

2022-09-17 06:39 UTC, scolladon approved these changes
LGTM

2022-09-17 07:18 UTC, merged

2022-09-17 07:32 UTC, scolladon commented
@rgarlik new version v2.2.0 is ready to be used, thanks to you mate !